### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by rehack** [zombie110year/tieba#2]
0it [00:00, ?it/s]Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\dev\python\Scripts\tiebamd.exe\__main__.py", line 7, in <module>
  File "D:\dev\python\Lib\site-packages\tiebamd\cli.py", line 17, in cli
    start(args)
  File "D:\dev\python\Lib\site-packages\tiebamd\cli.py", line 32, in start
    tc.start(start_fid)
  File "D:\dev\python\Lib\site-packages\tiebamd\crawl.py", line 75, in start
    raise TiebaException("{}: 请求错误 ({}) {}".format(
tiebamd.exceptions.TiebaException: 1766018024: 请求错误 (0)

**Comment by zombie110year** [comment]
有段时间没用过这个项目了，从HTTP响应来看，应该是百度方面改了客户端验证，我没有能力破解这个。
